language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: z8eA2X0FI1e6W5d9rvgEd0txTeXt1VAHVk2Zt3JSRojWGyBRTnB2BjgbPAwq29aTiJTJmtmIcrerV3Vlyz9n6KnCoaovF1p3d8qVKao9d9s5EUKGbB+a3s6P5p5IESn+ztBSMzvmZqiXElOufIG8SYXMQI2xsrhuSU9XJ0OogMmV6Um2fvBPED4nNzJBo4mnLfxr1yjha5/nKSUsPn31zUARQyca40ONgBGNFmdjatyw+eNTM/awsFHUpp8IrHKt0Yhrluro9c3Zx7w2Gc/zaDQShCG5tVDLoiyUx2FoIVXs0Sct+Z6DE/146jmjExk6qSqdQo6bbds3E22+Af5T54pTxk3UxbIoI7Cm+3G1Cf0wycGE7yzqBVPTzq4gMiAsM0swwNGk5XyAE41dAmb5lLwd2/qOoA/AF71YhQq/7mp7M38ooBYrCPGsOCg3RvFBAWf6rmfC1nDYc5c6Cf2He8RvVMUqKOMrSX/ARZV8Voj3SPUVYJOV8Y/WpJuuLFaO+Y3zX5X1CxnoWK7lreXZZZNC3zN6z6TnN/14cjE2CQEBU/ecyviBKCvJcLHJ3iyNiuBGb/D2aCShLHCrC1d+FeVGTLo56v3i43w1BGkV6fraN7UhoVULiEf3ukW1sMCIyEECd0pykLh3e6eSE8YoAI2S94+tNbwValL6q37p9Ug=
  app: sundarban-kartik-app
